import {DisplayBrand} from '../../../src/display/DisplayHeader'
import {useState} from 'react'
import './prototype.css'
const tasks=[
 ['Add PT tomorrow at 3:15 PM for 45 minutes.','Tomorrow is Wednesday, Oct 7. Success: PT spans 3:15–4:00 PM for Soren.'],
 ['Move it to 4:00 PM.','Use the move grip, arrow keys, or open the event. Success: PT spans 4:00–4:45 PM. Try resizing it, then Undo.'],
 ['Replace an existing activity.','Tap a local event and choose a different activity. Success: the same event shows the new picture, label, default duration and context.'],
 ['Create a new Activity inline and schedule it.','Use New Activity in the Add sheet. Choose a name and picture. Success: you return to the event with the new activity selected. Try a new person/place too.'],
 ["Copy a day’s schedule.",'Open a day, choose Copy day, and pick another date. Success: copied local activities appear on the destination; existing events remain. Try the School Day, Weekend and No School routines.'],
 ['Include three imported events for one profile.','Open Imported Events on a 7-day or Month calendar. Select three cards, choose only Soren, then Include selected. Success: those activities appear in Soren’s child view, while pending imports and Siv’s schedule are unchanged.'],
]
export function SchedulingTasks(){
 const [checked,setChecked]=useState<number[]>([])
 return <div className="sp-app"><main className="sp-task-page"><DisplayBrand compact/><p className="sp-muted">DEVELOPMENT STUDY · TYLER & LORI</p><h1>Where you see it,<br/>you can edit it.</h1><p>Use these tasks in order. All names and schedules are fictional. Today is frozen at October 6, 2026, 2:30 PM. Reloading resets changes.</p><div className="sp-chips"><a href="./scheduling-prototype.html?scenario=family" target="_blank" rel="noreferrer">Open family prototype ↗</a><a href="./scheduling-prototype.html?scenario=residential" target="_blank" rel="noreferrer">Open residential prototype ↗</a></div><p>Start in the normal display: profile avatar → Caregiver tools → Simulate unlock. You stay on the same schedule. No production PIN or login is involved.</p><ol className="sp-task-list">{tasks.map(([title,hint],i)=><li key={title}><label htmlFor={`task-${i}`}>{title}<small>{hint}</small></label><input id={`task-${i}`} type="checkbox" aria-label={`Complete task ${i+1}`} checked={checked.includes(i)} onChange={e=>setChecked(ids=>e.target.checked?[...ids,i]:ids.filter(id=>id!==i))}/></li>)}</ol><p role="status">{checked.length} of {tasks.length} tasks completed · Checklist stays only in this tab.</p><details><summary>Additional review prompts</summary><ul><li>Switch between Soren and Siv. Does each person’s visibility choice stay independent?</li><li>Try Now + Next, 1–7 days, 2–4 weeks and Month. Is “how much schedule” clearer than choosing a display mode?</li><li>Use the residential fixture’s 15-minute activities. Move and resize an overlapping event with touch or a mouse.</li><li>Include one recurring imported appointment for both profiles. Try “Apply to future events with this title?”.</li><li>Choose Done. Confirm editing controls and pending imports disappear.</li><li>Note unclear labels, unexpected results, task completion time, and anything you needed help finding. Keep notes separately.</li></ul></details></main></div>
}
