import {useRef,useState} from 'react'
import {DisplayBrand} from '../../../src/display/DisplayHeader'
import {ProfileAvatar} from '../../../src/profiles/ProfileChooser'
import {Art,Sheet} from './Shared'
import {visibleTimelineMinute} from './timelineInteraction'
import {CalendarBoard} from './CalendarBoard'
import type {WeekScrollPosition} from './calendarInteraction'
import {CaregiverSetup} from './CaregiverSetup'
import {DayCanvas} from './DayCanvas'
import {EventSheet} from './EventSheet'
import {ImportSheet} from './ImportSheet'
import {TODAY,NOW,ROUTINES,currentAndNext,restoreScheduleSnapshot,addDays,applyRoutine,copyDay,createFixture,formatDate,formatTime,ordered,rangeDates,reviewImports,shiftRange,visibleEvents,type PrototypeData,type PrototypeEvent} from './model'
import {fixtureLinks,type PrototypeLinks} from './links'
import './prototype.css'
export function SchedulingPrototype({scenario,links=fixtureLinks,initialSetup=false}:{scenario:'family'|'residential';links?:PrototypeLinks;initialSetup?:boolean}) {
 const [data,setData]=useState(()=>createFixture(scenario)),[history,setHistory]=useState<PrototypeData[]>([]),[message,setMessage]=useState('')
 const [profileId,setProfileId]=useState(data.profiles[0].id),[editing,setEditing]=useState(false),[menu,setMenu]=useState<'profiles'|'unlock'>()
 const [calendarOverride,setCalendarOverride]=useState(false),[anchor,setAnchor]=useState(TODAY),[focusDay,setFocusDay]=useState<string>(),[review,setReview]=useState(false),[selected,setSelected]=useState<string[]>([])
 const [bulkProfiles,setBulkProfiles]=useState<string[]>([profileId]),[bulkActivity,setBulkActivity]=useState(''),[sheet,setSheet]=useState<{date:string;start:number;event?:PrototypeEvent;initialMove?:boolean}>(),[importEvent,setImportEvent]=useState<PrototypeEvent>()
 const [setup,setSetup]=useState(()=>initialSetup||new URLSearchParams(location.search).get('setup')==='1'),calendarScroll=useRef(0)
 const [weekScrollPositions]=useState(()=>new Map<string,WeekScrollPosition>())
 const [dayAction,setDayAction]=useState<'copy'|'routine'>(),[destination,setDestination]=useState(addDays(TODAY,1)),[routine,setRoutine]=useState('School Day')
 const profile=data.profiles.find(p=>p.id===profileId)!,horizon=calendarOverride?7:profile.visibility,date=focusDay??anchor
 const accepted=visibleEvents(data,profileId),pending=ordered(data.events.filter(e=>e.origin==='imported'&&e.review==='pending'&&!e.cancelled))
 const dates=rangeDates(anchor,horizon),rangePending=pending.filter(e=>dates.includes(e.date)),selection=selected.filter(id=>rangePending.some(e=>e.id===id))
 const dayEvents=accepted.filter(e=>e.date===date)
 const commit=(next:PrototypeData,text:string)=>{setHistory(h=>[...h.slice(-19),data]);setData(next);setMessage(text);setSelected([])}
 const undo=()=>{const previous=history.at(-1);if(previous){setData(restoreScheduleSnapshot(data,previous));setHistory(h=>h.slice(0,-1));setMessage('Change undone.');setSelected([])}}
 const openDay=(value:string)=>{if(!isDay)calendarScroll.current=window.scrollY;setFocusDay(value);setReview(false)}
 const showAll=()=>{if(horizon===0||horizon===1)setCalendarOverride(true);setFocusDay(undefined);setReview(false);requestAnimationFrame(()=>window.scrollTo({top:calendarScroll.current,behavior:'instant'}))}
 const editEvent=(event:PrototypeEvent)=>{if(!editing)return;if(event.origin==='imported')setImportEvent(event);else setSheet({date:event.date,start:event.start,event})}
 const onMove=(event:PrototypeEvent)=>commit({...data,events:data.events.map(e=>e.id===event.id?event:e)},`${data.activities.find(a=>a.id===event.activityId)?.name} · ${formatDate(event.date)} · ${formatTime(event.start)} – ${formatTime(event.end)}`)
 const startReview=()=>{setReview(v=>!v);setFocusDay(undefined);setSelected([]);setBulkProfiles([profileId]);if(horizon===0||horizon===1)setCalendarOverride(true)}
 const bulk=(decision:'included'|'ignored')=>{commit(reviewImports(data,selection,decision,bulkProfiles,bulkActivity||undefined),`${selection.length} imported events ${decision==='included'?'included':'ignored'}.`)}
 const isDay=Boolean(focusDay)||horizon===1,isNow=horizon===0&&!focusDay
 const addAtVisibleTime=()=>{
  const canvas=isDay?document.querySelector<HTMLElement>('.sp-day-canvas'):null
  const start=canvas?visibleTimelineMinute(Number(canvas.dataset.start),Number(canvas.dataset.end),canvas.getBoundingClientRect().top,document.querySelector('.sp-editing-bar')?.getBoundingClientRect().bottom??0,Number(getComputedStyle(canvas).getPropertyValue('--sp-minute-px'))):15*60+15
  setSheet({date,start})
 }
 const recentNow=currentAndNext(accepted)
 const backLabel=horizon==='month'?'MONTH':horizon>7?`${Number(horizon)/7} WEEKS`:horizon>=2&&horizon<7?`${horizon} DAYS`:'WEEK'
 const toggleEditing=(value:boolean)=>{
  const canvas=document.querySelector('.sp-day-canvas'),before=canvas?Math.max(0,document.querySelector('.sp-editing-bar')?.getBoundingClientRect().bottom??0)-canvas.getBoundingClientRect().top:undefined
  setEditing(value)
  if(before!==undefined)requestAnimationFrame(()=>{const next=document.querySelector('.sp-day-canvas');if(next)window.scrollBy(0,before-(Math.max(0,document.querySelector('.sp-editing-bar')?.getBoundingClientRect().bottom??0)-next.getBoundingClientRect().top))})
 }
 const openSetup=()=>{setMenu(undefined);setSetup(true)}
 return <div className="sp-app">
  <aside className="sp-lab-bar"><span><b>Interaction prototype</b> · Fictional {scenario==='family'?'family':'residential'} data · Today: Oct 6, 2026 · Changes reset on reload</span><nav aria-label="Prototype scenarios">{links.home&&<a href={links.home}>Home</a>}<a href={links.family} aria-current={scenario==='family'?'page':undefined}>Family</a><a href={links.residential} aria-current={scenario==='residential'?'page':undefined}>Residential</a><a href={links.tasks}>Usability tasks ↗</a><button onClick={openSetup}>Caregiver Setup</button></nav></aside>
  <main className="sp-workspace" data-day={isDay}>
   <header className="sp-display-header"><DisplayBrand/><div><p>{profile.name}’s schedule</p><h1>{isDay?formatDate(date,{weekday:'long'}):isNow?'NOW + NEXT':horizon==='month'?formatDate(anchor,{month:'long'}):`${horizon} DAYS`}</h1></div><button className="sp-profile-menu" aria-label={`Profile menu for ${profile.name}`} onClick={()=>setMenu('profiles')}><ProfileAvatar profile={profile}/><span>{profile.name} ⌄</span></button></header>
   {editing&&<section className="sp-editing-bar" aria-label="Caregiver editing tools"><div className="sp-editing-main">{isDay&&<button className="sp-secondary sp-back-button" onClick={showAll}>← {backLabel}</button>}<strong><span aria-hidden="true">●</span> EDITING {profile.name.toUpperCase()}</strong><button aria-label="Add Activity" onClick={addAtVisibleTime}>＋ Add<span className="sp-add-label"> Activity</span></button><button className="sp-secondary" onClick={()=>{toggleEditing(false);setReview(false);setSelected([]);setMessage('Editing finished. Child display restored.')}}>Done</button></div><div className="sp-editing-options" role="group" aria-label="More caregiver actions"><button className="sp-secondary" onClick={openSetup}>Caregiver Setup</button><button className="sp-secondary" onClick={()=>{setDayAction('copy');setDestination(addDays(date,1))}}>Copy day</button><button className="sp-secondary" onClick={()=>{setDayAction('routine');setDestination(date)}}>Apply routine</button>{scenario==='family'&&<button className="sp-secondary" aria-pressed={review} onClick={startReview}>Imported Events <span className="sp-count">{pending.length}</span></button>}<button className="sp-secondary" disabled={!history.length} onClick={undo}>Undo</button></div></section>}
   <div className="sp-calendar-toolbar">
    <div><h2>{isDay?formatDate(date,{month:'long',day:'numeric',year:'numeric'}):isNow?formatDate(TODAY):horizon==='month'?formatDate(anchor,{year:'numeric'}):`${formatDate(dates[0],{month:'short',day:'numeric'})} – ${formatDate(dates.at(-1)!,{month:'short',day:'numeric'})}`}</h2></div>
    {editing&&!isNow&&<nav aria-label="Schedule dates"><button className="sp-secondary" aria-label="Previous dates" onClick={()=>focusDay?setFocusDay(addDays(focusDay,-1)):setAnchor(shiftRange(anchor,horizon,-1))}>←</button><button className="sp-secondary" onClick={()=>{setAnchor(TODAY);weekScrollPositions.delete(`${profileId}:${TODAY}:${horizon}`);document.querySelector<HTMLElement>('.sp-calendar[data-week=true]')?.scrollTo({left:0,behavior:'instant'});if(focusDay)setFocusDay(TODAY)}}>Today</button><button className="sp-secondary" aria-label="Next dates" onClick={()=>focusDay?setFocusDay(addDays(focusDay,1)):setAnchor(shiftRange(anchor,horizon,1))}>→</button></nav>}
   </div>
   {editing&&<p className="sp-change-status" role="status">{message||'Tap a day or activity to edit it right here.'}</p>}
   {review&&editing&&<section className="sp-review-bar" aria-label="Imported Events review"><div><h2>Imported Events</h2><p>Only you can see unreviewed imports. Select cards, then include or ignore them.</p></div><div className="sp-chips"><button className="sp-secondary" disabled={!rangePending.length} onClick={()=>setSelected(selection.length===rangePending.length?[]:rangePending.map(e=>e.id))}>{selection.length===rangePending.length&&selection.length?'Clear selection':'Select this range'}</button><b>{selection.length} selected</b></div><fieldset><legend>Show on</legend><div className="sp-chips">{data.profiles.map(p=><label key={p.id}><input type="checkbox" checked={bulkProfiles.includes(p.id)} onChange={e=>setBulkProfiles(ids=>e.target.checked?[...ids,p.id]:ids.filter(id=>id!==p.id))}/>{p.name}</label>)}<label>Activity<select value={bulkActivity} onChange={e=>setBulkActivity(e.target.value)}><option value="">Use each suggestion</option>{data.activities.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div></fieldset><div className="sp-chips"><button disabled={!selection.length||!bulkProfiles.length} onClick={()=>bulk('included')}>Include selected</button><button className="sp-secondary" disabled={!selection.length} onClick={()=>bulk('ignored')}>Ignore selected</button></div></section>}
   {isDay?<><p className="sp-day-help">{editing?'Tap to edit. Swipe to scroll. Hold an activity to move, or drag ⠿. The duration handle resizes; arrow keys adjust 15 minutes.':''}</p><DayCanvas key={profileId+date} data={data} date={date} events={dayEvents} editing={editing} onAdd={time=>setSheet({date,start:time})} onEdit={editEvent} onMove={onMove}/></>:isNow?<><div className="sp-now-cards">{recentNow.map((event,i)=>{const a=data.activities.find(a=>a.id===event.activityId)!;return <article key={event.id}><h2>{i===0&&event.date===TODAY&&event.start<=NOW?'NOW':i===0?'NEXT':'NEXT'}</h2>{editing?<button onClick={()=>editEvent(event)}><Art kind={a.kind}/><strong>{a.name.toUpperCase()}</strong></button>:<><Art kind={a.kind}/><strong>{a.name.toUpperCase()}</strong></>}<p>{data.places.find(p=>p.id===event.placeId)?.name}</p></article>})}</div>{editing&&<button className="sp-secondary" onClick={()=>openDay(TODAY)}>Open today’s timeline</button>}</>:<CalendarBoard key={`${profileId}:${anchor}:${horizon}:${editing}:${review}`} scrollPositions={weekScrollPositions} scrollKey={`${profileId}:${anchor}:${horizon}`} data={data} dates={dates} events={review?pending:ordered([...accepted,...(editing?pending:[])])} editing={editing} review={review} compact={horizon==='month'||Number(horizon)>7} month={horizon==='month'} monthDate={anchor} onMove={onMove} onMovePick={event=>setSheet({date:event.date,start:event.start,event,initialMove:true})} selected={selection} onSelect={id=>setSelected(ids=>ids.includes(id)?ids.filter(i=>i!==id):[...ids,id])} onDay={openDay} onEvent={editEvent} onAdd={d=>setSheet({date:d,start:15*60+15})}/>}
   {!editing&&<p className="sp-child-hint">{isDay?'MY DAY':isNow?'':'TAP A DAY'}</p>}
  </main>
  {isDay&&!editing&&<button className="sp-child-back sp-secondary" onClick={showAll}>← {backLabel}</button>}
  {isDay&&!editing&&<button className="sp-caregiver-trigger sp-secondary" aria-label="Caregiver tools" onClick={()=>setMenu('unlock')}><span aria-hidden="true">⚙</span><span>Caregiver tools</span></button>}
  {setup&&<CaregiverSetup data={data} onClose={()=>setSetup(false)} onSave={(next,id)=>{setData(next);if(id===profileId&&next.profiles.find(p=>p.id===id)?.visibility!==profile.visibility){setFocusDay(undefined);setCalendarOverride(false);setAnchor(TODAY);setReview(false);setSelected([])}}}/>}
  {menu&&<Sheet title={menu==='profiles'?'Who’s using SOREN?':'Caregiver access · simulation'} onClose={()=>setMenu(undefined)}>{menu==='profiles'?<div className="sp-editor-form"><div className="sp-profile-choices">{data.profiles.map(p=><button key={p.id} aria-pressed={profileId===p.id} onClick={()=>{setProfileId(p.id);setEditing(false);setReview(false);setSelected([]);setFocusDay(undefined);setAnchor(TODAY);setCalendarOverride(false);setMenu(undefined);window.scrollTo({top:0,behavior:'instant'})}}><ProfileAvatar profile={p}/><strong>{p.name}</strong></button>)}</div><button onClick={()=>setMenu('unlock')}>Caregiver tools</button><button className="sp-secondary" onClick={openSetup}>Caregiver Setup</button></div>:<div className="sp-editor-form"><p>This fictional fixture simulates caregiver permission. No PIN, account, or household connection is used.</p><p>You will edit {profile.name}’s schedule on this screen.</p><footer><button className="sp-secondary" onClick={()=>setMenu('profiles')}>Cancel</button><button onClick={()=>{toggleEditing(true);setMenu(undefined);setMessage('Editing unlocked for this fictional session.')}}>Simulate unlock</button></footer></div>}</Sheet>}
  {sheet&&editing&&<EventSheet key={sheet.event?.id??sheet.date+sheet.start} data={data} profileId={profileId} {...sheet} onClose={()=>setSheet(undefined)} onMoved={openDay} onSave={commit}/>}
  {importEvent&&editing&&<ImportSheet data={data} event={importEvent} profileId={profileId} onClose={()=>setImportEvent(undefined)} onSave={commit}/>}
  {dayAction&&<Sheet title={dayAction==='copy'?'Copy day':'Apply routine'} onClose={()=>setDayAction(undefined)}><form className="sp-editor-form" onSubmit={e=>{e.preventDefault();if(!destination)return;commit(dayAction==='copy'?copyDay(data,profileId,date,destination,()=>crypto.randomUUID()):applyRoutine(data,profileId,destination,routine,()=>crypto.randomUUID()),dayAction==='copy'?'Day copied. Existing events kept.':'Routine added. Existing events kept.');setDayAction(undefined);openDay(destination)}}>
   <p>{dayAction==='copy'?`Copy ${profile.name}’s accepted activities from ${formatDate(date)}.`:'Start with a familiar day. Adjust any event afterward.'}</p>
   {dayAction==='routine'&&<div className="sp-routine-options">{Object.entries(ROUTINES).map(([name,slots])=><button key={name} type="button" aria-pressed={routine===name} onClick={()=>setRoutine(name)}><strong>{name}</strong><small>{slots.map(s=>data.activities.find(a=>a.id===s.activityId)?.name).join(' · ')}</small></button>)}</div>}
   <label>{dayAction==='copy'?'Copy to':'Apply on'}<input required type="date" value={destination} onChange={e=>setDestination(e.target.value)}/></label><p className="sp-muted">Adds local activities for {profile.name} only. Existing events remain; overlaps are shown side by side. Undo is available.</p><footer><button type="button" className="sp-secondary" onClick={()=>setDayAction(undefined)}>Cancel</button><button disabled={!destination||(dayAction==='copy'&&(destination===date||!dayEvents.length))}>{dayAction==='copy'?'Copy day':'Apply routine'}</button></footer>
  </form></Sheet>}
 </div>
}
