import {useState} from 'react'
import {DisplayBrand} from '../../../src/display/DisplayHeader'
import {ProfileAvatar} from '../../../src/profiles/ProfileChooser'
import {Art,Sheet} from './Shared'
import {CalendarBoard} from './CalendarBoard'
import {DayCanvas} from './DayCanvas'
import {EventSheet} from './EventSheet'
import {ImportSheet} from './ImportSheet'
import {TODAY,NOW,HORIZONS,ROUTINES,addDays,applyRoutine,copyDay,createFixture,formatDate,formatTime,ordered,rangeDates,reviewImports,shiftRange,visibleEvents,type Horizon,type PrototypeData,type PrototypeEvent} from './model'
import './prototype.css'
export function SchedulingPrototype({scenario}:{scenario:'family'|'residential'}) {
 const [data,setData]=useState(()=>createFixture(scenario)),[history,setHistory]=useState<PrototypeData[]>([]),[message,setMessage]=useState('')
 const [profileId,setProfileId]=useState(data.profiles[0].id),[editing,setEditing]=useState(false),[menu,setMenu]=useState<'profiles'|'unlock'>()
 const [horizons,setHorizons]=useState<Record<string,Horizon>>({}),[anchor,setAnchor]=useState(TODAY),[focusDay,setFocusDay]=useState<string>(),[review,setReview]=useState(false),[selected,setSelected]=useState<string[]>([])
 const [bulkProfiles,setBulkProfiles]=useState<string[]>([profileId]),[bulkActivity,setBulkActivity]=useState(''),[sheet,setSheet]=useState<{date:string;start:number;event?:PrototypeEvent}>(),[importEvent,setImportEvent]=useState<PrototypeEvent>()
 const [dayAction,setDayAction]=useState<'copy'|'routine'>(),[destination,setDestination]=useState(addDays(TODAY,1)),[routine,setRoutine]=useState('School Day')
 const profile=data.profiles.find(p=>p.id===profileId)!,horizon=horizons[profileId]??(scenario==='family'?7:1),date=focusDay??anchor
 const accepted=visibleEvents(data,profileId),pending=ordered(data.events.filter(e=>e.origin==='imported'&&e.review==='pending'&&!e.cancelled))
 const dates=rangeDates(anchor,horizon),rangePending=pending.filter(e=>dates.includes(e.date)),selection=selected.filter(id=>rangePending.some(e=>e.id===id))
 const dayEvents=accepted.filter(e=>e.date===date)
 const commit=(next:PrototypeData,text:string)=>{setHistory(h=>[...h.slice(-19),data]);setData(next);setMessage(text);setSelected([])}
 const undo=()=>{const previous=history.at(-1);if(previous){setData(previous);setHistory(h=>h.slice(0,-1));setMessage('Change undone.');setSelected([])}}
 const openDay=(value:string)=>{setFocusDay(value);setReview(false);window.scrollTo({top:0,behavior:'instant'})}
 const showAll=()=>{setFocusDay(undefined);setReview(false)}
 const changeHorizon=(value:Horizon)=>{setHorizons(h=>({...h,[profileId]:value}));setFocusDay(undefined);setReview(false);setSelected([])}
 const editEvent=(event:PrototypeEvent)=>{if(!editing)return;if(event.origin==='imported')setImportEvent(event);else setSheet({date:event.date,start:event.start,event})}
 const onMove=(event:PrototypeEvent)=>commit({...data,events:data.events.map(e=>e.id===event.id?event:e)},`${data.activities.find(a=>a.id===event.activityId)?.name} · ${formatTime(event.start)} – ${formatTime(event.end)}`)
 const startReview=()=>{setReview(v=>!v);setFocusDay(undefined);setSelected([]);setBulkProfiles([profileId]);if(horizon===0||horizon===1)setHorizons(h=>({...h,[profileId]:7}))}
 const bulk=(decision:'included'|'ignored')=>{commit(reviewImports(data,selection,decision,bulkProfiles,bulkActivity||undefined),`${selection.length} imported events ${decision==='included'?'included':'ignored'}.`)}
 const isDay=Boolean(focusDay)||horizon===1,isNow=horizon===0&&!focusDay
 const recentNow=accepted.filter(e=>e.date>TODAY||(e.date===TODAY&&e.end>NOW)).slice(0,2)
 return <div className="sp-app">
  <aside className="sp-lab-bar"><span><b>Interaction prototype</b> · Fictional {scenario==='family'?'family':'residential'} data · Today: Oct 6, 2026 · Changes reset on reload</span><nav aria-label="Prototype scenarios"><a href="?scenario=family" aria-current={scenario==='family'?'page':undefined}>Family</a><a href="?scenario=residential" aria-current={scenario==='residential'?'page':undefined}>Residential</a><a href="./scheduling-tasks.html">Usability tasks ↗</a></nav></aside>
  <main className="sp-workspace">
   <header className="sp-display-header"><DisplayBrand/><div><p>{profile.name}’s schedule</p><h1>{isDay?formatDate(date,{weekday:'long'}):isNow?'NOW + NEXT':horizon==='month'?formatDate(anchor,{month:'long'}):`${horizon} DAYS`}</h1></div><button className="sp-profile-menu" aria-label={`Profile menu for ${profile.name}`} onClick={()=>setMenu('profiles')}><ProfileAvatar profile={profile}/><span>{profile.name} ⌄</span></button></header>
   {editing&&<section className="sp-editing-bar" aria-label="Caregiver editing tools"><div className="sp-editing-main"><strong><span aria-hidden="true">●</span> EDITING {profile.name.toUpperCase()}</strong><button onClick={()=>setSheet({date,start:15*60+15})}>＋ Add Activity</button><button className="sp-secondary" onClick={()=>{setEditing(false);setReview(false);setSelected([]);setMessage('Editing finished. Child display restored.')}}>Done</button></div><div className="sp-editing-options"><label>How much schedule should this person see?<select value={String(horizon)} onChange={e=>changeHorizon(e.target.value==='month'?'month':Number(e.target.value) as Horizon)}>{HORIZONS.map(h=><option key={h.value} value={h.value}>{h.label}</option>)}</select></label><div className="sp-chips"><button className="sp-secondary" onClick={()=>{setDayAction('copy');setDestination(addDays(date,1))}}>Copy day</button><button className="sp-secondary" onClick={()=>{setDayAction('routine');setDestination(date)}}>Apply routine</button>{scenario==='family'&&<button className="sp-secondary" aria-pressed={review} onClick={startReview}>Imported Events <span className="sp-count">{pending.length}</span></button>}<button className="sp-secondary" disabled={!history.length} onClick={undo}>Undo</button></div></div></section>}
   <div className="sp-calendar-toolbar">
    <div>{focusDay&&horizon!==1&&<button className="sp-secondary" onClick={showAll}>← {horizon==='month'?'Month':horizon===0?'Now + Next':`${horizon} days`}</button>}<h2>{isDay?formatDate(date,{month:'long',day:'numeric',year:'numeric'}):isNow?formatDate(TODAY):horizon==='month'?formatDate(anchor,{year:'numeric'}):`${formatDate(dates[0],{month:'short',day:'numeric'})} – ${formatDate(dates.at(-1)!,{month:'short',day:'numeric'})}`}</h2></div>
    {editing&&!isNow&&<nav aria-label="Schedule dates"><button className="sp-secondary" aria-label="Previous dates" onClick={()=>focusDay?setFocusDay(addDays(focusDay,-1)):setAnchor(shiftRange(anchor,horizon,-1))}>←</button><button className="sp-secondary" onClick={()=>{setAnchor(TODAY);if(focusDay)setFocusDay(TODAY)}}>Today</button><button className="sp-secondary" aria-label="Next dates" onClick={()=>focusDay?setFocusDay(addDays(focusDay,1)):setAnchor(shiftRange(anchor,horizon,1))}>→</button></nav>}
   </div>
   {editing&&<p className="sp-change-status" role="status">{message||'Tap a day or activity to edit it right here.'}</p>}
   {review&&editing&&<section className="sp-review-bar" aria-label="Imported Events review"><div><h2>Imported Events</h2><p>Only you can see unreviewed imports. Select cards, then include or ignore them.</p></div><div className="sp-chips"><button className="sp-secondary" disabled={!rangePending.length} onClick={()=>setSelected(selection.length===rangePending.length?[]:rangePending.map(e=>e.id))}>{selection.length===rangePending.length&&selection.length?'Clear selection':'Select this range'}</button><b>{selection.length} selected</b></div><fieldset><legend>Show on</legend><div className="sp-chips">{data.profiles.map(p=><label key={p.id}><input type="checkbox" checked={bulkProfiles.includes(p.id)} onChange={e=>setBulkProfiles(ids=>e.target.checked?[...ids,p.id]:ids.filter(id=>id!==p.id))}/>{p.name}</label>)}<label>Activity<select value={bulkActivity} onChange={e=>setBulkActivity(e.target.value)}><option value="">Use each suggestion</option>{data.activities.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div></fieldset><div className="sp-chips"><button disabled={!selection.length||!bulkProfiles.length} onClick={()=>bulk('included')}>Include selected</button><button className="sp-secondary" disabled={!selection.length} onClick={()=>bulk('ignored')}>Ignore selected</button></div></section>}
   {isDay?<><p className="sp-day-help">{editing?'Tap empty time to add. Drag ⠿ to move; drag the bottom handle to resize. Arrow keys also adjust 15 minutes. Overlaps sit side by side.':''}</p><DayCanvas data={data} events={dayEvents} editing={editing} onAdd={time=>setSheet({date,start:time})} onEdit={editEvent} onMove={onMove}/></>:isNow?<><div className="sp-now-cards">{recentNow.map((event,i)=>{const a=data.activities.find(a=>a.id===event.activityId)!;return <article key={event.id}><h2>{i===0&&event.date===TODAY&&event.start<=NOW?'NOW':i===0?'NEXT':'NEXT'}</h2>{editing?<button onClick={()=>editEvent(event)}><Art kind={a.kind}/><strong>{a.name.toUpperCase()}</strong></button>:<><Art kind={a.kind}/><strong>{a.name.toUpperCase()}</strong></>}<p>{data.places.find(p=>p.id===event.placeId)?.name}</p></article>})}</div>{editing&&<button className="sp-secondary" onClick={()=>openDay(TODAY)}>Open today’s timeline</button>}</>:<CalendarBoard data={data} dates={dates} events={review?pending:ordered([...accepted,...(editing?pending:[])])} editing={editing} review={review} compact={horizon==='month'||Number(horizon)>7} selected={selection} onSelect={id=>setSelected(ids=>ids.includes(id)?ids.filter(i=>i!==id):[...ids,id])} onDay={openDay} onEvent={editEvent} onAdd={d=>setSheet({date:d,start:15*60+15})}/>}
   {!editing&&<p className="sp-child-hint">{isDay?'MY DAY':isNow?'':'TAP A DAY'}</p>}
  </main>
  {menu&&<Sheet title={menu==='profiles'?'Who’s using SOREN?':'Caregiver access · simulation'} onClose={()=>setMenu(undefined)}>{menu==='profiles'?<div className="sp-editor-form"><div className="sp-profile-choices">{data.profiles.map(p=><button key={p.id} aria-pressed={profileId===p.id} onClick={()=>{setProfileId(p.id);setEditing(false);setReview(false);setSelected([]);setFocusDay(undefined);setAnchor(TODAY);setMenu(undefined)}}><ProfileAvatar profile={p}/><strong>{p.name}</strong></button>)}</div><button onClick={()=>setMenu('unlock')}>Caregiver tools</button></div>:<div className="sp-editor-form"><p>This fictional fixture simulates caregiver permission. No PIN, account, or household connection is used.</p><p>You will edit {profile.name}’s schedule on this screen.</p><footer><button className="sp-secondary" onClick={()=>setMenu('profiles')}>Cancel</button><button onClick={()=>{setEditing(true);setMenu(undefined);setMessage('Editing unlocked for this fictional session.')}}>Simulate unlock</button></footer></div>}</Sheet>}
  {sheet&&editing&&<EventSheet key={sheet.event?.id??sheet.date+sheet.start} data={data} profileId={profileId} {...sheet} onClose={()=>setSheet(undefined)} onSave={commit}/>}
  {importEvent&&editing&&<ImportSheet data={data} event={importEvent} profileId={profileId} onClose={()=>setImportEvent(undefined)} onSave={commit}/>}
  {dayAction&&<Sheet title={dayAction==='copy'?'Copy day':'Apply routine'} onClose={()=>setDayAction(undefined)}><form className="sp-editor-form" onSubmit={e=>{e.preventDefault();if(!destination)return;commit(dayAction==='copy'?copyDay(data,profileId,date,destination,()=>crypto.randomUUID()):applyRoutine(data,profileId,destination,routine,()=>crypto.randomUUID()),dayAction==='copy'?'Day copied. Existing events kept.':'Routine added. Existing events kept.');setDayAction(undefined);openDay(destination)}}>
   <p>{dayAction==='copy'?`Copy ${profile.name}’s accepted activities from ${formatDate(date)}.`:'Start with a familiar day. Adjust any event afterward.'}</p>
   {dayAction==='routine'&&<div className="sp-routine-options">{Object.entries(ROUTINES).map(([name,slots])=><button key={name} type="button" aria-pressed={routine===name} onClick={()=>setRoutine(name)}><strong>{name}</strong><small>{slots.map(s=>data.activities.find(a=>a.id===s.activityId)?.name).join(' · ')}</small></button>)}</div>}
   <label>{dayAction==='copy'?'Copy to':'Apply on'}<input required type="date" value={destination} onChange={e=>setDestination(e.target.value)}/></label><p className="sp-muted">Adds local activities for {profile.name} only. Existing events remain; overlaps are shown side by side. Undo is available.</p><footer><button type="button" className="sp-secondary" onClick={()=>setDayAction(undefined)}>Cancel</button><button disabled={!destination||(dayAction==='copy'&&(destination===date||!dayEvents.length))}>{dayAction==='copy'?'Copy day':'Apply routine'}</button></footer>
  </form></Sheet>}
 </div>
}
